spring:
  datasource:
    name: rong_mu_user
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    druid:
      name: rong_mu_user
      #中文p
      filters: statq
      driver-class-name: com.mysql.cj.jdbc.Driver
      #
      url: jdbc:mysql://rm-2zeqb6p473149ntco125010gm.mysql.rds.aliyuncs.com:3306/rong_mu_user?generateSimpleParameterMetadata=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: rong_mu_1
      password: 1qaz2wsX
      #
      initial-size: 1
      min-idle: 1
      max-active: 20
      #
      max-wait: 60000
      #
      time-between-eviction-runs-millis: 60000
      #
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
