spring:
  datasource:
    name: 52ydwftest_db
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    druid:
      name: 52ydwftest_db
      #中文p
      filters: statq
      driver-class-name: com.mysql.cj.jdbc.Driver
      #
      url: jdbc:mysql://192.168.28.134:3306/face_server?generateSimpleParameterMetadata=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: service
      password: servicedb!
      #
      initial-size: 1
      min-idle: 1
      max-active: 20
      #
      max-wait: 60000
      #
      time-between-eviction-runs-millis: 60000
      #
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
